### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by mondeja** [mondeja/simple-icons-website-rs#1]
- [x] Button to go to the footer of the page (https://github.com/mondeja/simple-icons-website-rs/commit/2f6a80b48e741382e262c3cd59a215dc988f885a)
- [x] Button to continue loading more icons when the user is in the footer (https://github.com/mondeja/simple-icons-website-rs/commit/2f6a80b48e741382e262c3cd59a215dc988f885a)
- [x] Manage state through URL (implemented on https://github.com/mondeja/simple-icons-website-rs/commit/3035829c7a8f24a5dfc38049810e665bbadf660a for search and language, enough for now).
- [x] Update and complete translations (https://github.com/mondeja/simple-icons-website-rs/commit/e1680568fd9d1d9ba346c7d0ed764cb4419edba7)
- [x] Readd aria support.
- [x] #3
- [x] Add CNAME (https://github.com/mondeja/simple-icons-website-rs/commit/fd48a534ccccba6427cf30f4e11a5d50c7dab837)
- [x] Publish under https://wasm.simpleicons.org
- [x] Add CI (#2)
- [x] Add `simple-icons` bump version script (#2)
- [x] Provide copying fallback for browsers that don't implement the unstable Clipboard API (https://github.com/mondeja/simple-icons-website-rs/commit/0757a858135337c4ae84e9555cd9160e23e98f8f) 
- [x] Fix styles of footer on small screens (https://github.com/mondeja/simple-icons-website-rs/commit/139b9e0653a230695d6c72d72c206ccab255046f)
- [x] Fix some styles in mobile for very small screens (footer is ugly and search bar collapses into controls toggler) (https://github.com/mondeja/simple-icons-website-rs/commit/15e68f8b90ad3439ff97a2f1fcfdf15a92fe281a)
- [x] Wait for wasm-bindgen crash fix or provide fallback redirection to current website on Webkit browsers.

**Comment by mondeja** [comment]
The website seems pretty stable now, the unique problem is that is just crashing on Webkit browsers due to be an error on the wasm-bindgen crate. I've opened an issue there (3389, not linking here to not bring more noise to it) with a MRE, but doesn't seems easy to fix.

So I'm going to  work on a few more features here to see if the fix could reach soon. If not, I need to provide a redirection to the old website with a custom snippet. The old website could be served at `http://webkit.simpleicons.org` and built from a repository at `https://github.com/simple-icons/simple-icons-old-website`. Using this solution we can ensure that Safari users are not left without access to the Simpleicons web interface while the bug is fixed.
